config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root 'books#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
       
       has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @book = current_user.books.find_by(id: params[:id])
    redirect_to books_path, notice: "Not Authorized" if @book.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:book_name, :author_name, :lib_name, :email, :phone, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def About
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_book.html.erb
<div class="jumbotron">
<h1 class="display-4">
<%= book.book_name %>
</h1>
<p class="lead"><strong>Author: </strong><%= book.author_name %></p>
<hr class="my-4">
<p>
<strong>Library name:</strong>
    <%= book.lib_name %> <br/>
<strong>Email:</strong>
    <%= book.email %><br/>
<strong>Phone:</strong>
    <%= book.phone %>
    <br/><br/>
</p>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br/>
  <div class="form-group">
    <%= form.text_field :book_name, class:"form-control", placeholder:"Book Name" %>
  </div>
          <br/>
  <div class="form-group">
    <%= form.text_field :author_name, class:"form-control", placeholder:"Author Name" %>
  </div>
  <br/>
  <div class="form-group">
    <%= form.text_field :lib_name, class:"form-control", placeholder:"Library Name" %>
  </div>
  <br/>
  <div class="form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email ID" %>
  </div>
  <br/>
  <div class="form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>
  <div class="form-group">
  <%= form.number_field :user_id, id: :book_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
  <br/>
  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book, class:"btn btn-dark" %> |
  <%= link_to "Back", books_path, class:"btn btn-dark" %>
</div>

app/views/books/index.html.erb
<% if user_signed_in? %>

  <table class="table table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th>First Name</th>
        <th>Author Name</th>
        <th>Library Name</th>
        <th>Email ID</th>
        <th>Phone No.</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
      <% if book.user == current_user %>
      <tr>
      <td><%= link_to book.book_name, book %></td>
      <td><%= book.author_name %></td>
      <td><%= book.lib_name %></td>
      <td><%= book.email %></td>
      <td><%= book.phone %></td>
      <td><%= button_to "Delete", book, method: :delete, class:"btn btn-danger" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
  </table>

  <%= link_to 'Add Book', new_book_path, class:"btn btn-dark" %>

<% else %>

<h1>Welcome to Book Store.</h1>
This is my First rails project.

<% end %>

app/views/books/new.html.erb
<h1>Add New Book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back", books_path, class:"btn btn-dark" %>
</div>

app/views/books/show.html.erb
<%= render @book %>

<div>
  <%= link_to "Edit", edit_book_path(@book), class:"btn btn-dark" %> |
  <%= link_to "Back", books_path, class:"btn btn-dark" %>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Rails App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link active" %>
          
    <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to 'Add Book', new_book_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link active" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link active" %>
        </li> 
    <% else %>
        <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class:"nav-link active" %>
        </li>
    <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us......</h1>

app/views/home/index.html.erb
<h1>Welcome to Book Store.</h1>

app/views/layouts/_alert.html.erb
<div class="alert alert-primary alert-dismissible fade show" role="alert">
<%= notice %>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rails Application</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    </head>
  <body>
  <%= render 'home/header' %>
  <div class="container">
  <br/>
  <% if notice %>
  <%= render 'layouts/alert' %>
  <% end %>
  <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>